// <auto-generated />
using System;
using Meezan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meezan.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260926155232_MakeIndexConstituentWeightNullable")]
    partial class MakeIndexConstituentWeightNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Meezan.Domain.Entities.Index", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Indices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EGX30",
                            Description = "Top 30 liquid and active companies",
                            NameAr = "المؤشر الرئيسي للبورصة المصرية EGX30",
                            NameEn = "EGX 30 Index"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EGX30TR",
                            Description = "EGX 30 Total Return Index including dividend reinvestment",
                            NameAr = "مؤشر العائد الكلي EGX30TR",
                            NameEn = "EGX 30 Total Return Index"
                        },
                        new
                        {
                            Id = 3,
                            Code = "EGX70",
                            Description = "EGX 70 Equal Weights Index",
                            NameAr = "مؤشر الشركات الصغيرة والمتوسطة EGX70 EWI",
                            NameEn = "EGX 70 EWI Index"
                        },
                        new
                        {
                            Id = 4,
                            Code = "EGX100",
                            Description = "EGX 100 Equal Weights Index",
                            NameAr = "المؤشر الأوسع نطاقاً EGX100 EWI",
                            NameEn = "EGX 100 EWI Index"
                        },
                        new
                        {
                            Id = 5,
                            Code = "EGX35-LV",
                            Description = "EGX 35 Low Volatility Index",
                            NameAr = "مؤشر التذبذب المنخفض EGX35-LV",
                            NameEn = "EGX 35 Low Volatility Index"
                        },
                        new
                        {
                            Id = 6,
                            Code = "Shariah",
                            Description = "Shariah Compliant Index",
                            NameAr = "مؤشر الشريعة EGX30 Shariah",
                            NameEn = "EGX 33 Shariah Index"
                        },
                        new
                        {
                            Id = 7,
                            Code = "Sectoral-Indices",
                            Description = "EGX Sectoral Indices Constituents",
                            NameAr = "المؤشرات القطاعية",
                            NameEn = "Sectoral Indices"
                        },
                        new
                        {
                            Id = 8,
                            Code = "TAMAYUZ",
                            Description = "Tamayuz Small & Medium Enterprises Index",
                            NameAr = "مؤشر سوق الشركات الصغيرة والمتوسطة تميز",
                            NameEn = "Tamayuz Index"
                        });
                });

            modelBuilder.Entity("Meezan.Domain.Entities.IndexConstituent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndexId")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("IndexId", "StockId");

                    b.ToTable("IndexConstituents", (string)null);
                });

            modelBuilder.Entity("Meezan.Domain.Entities.ScrapeRunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("FailedStocks")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SucceededStocks")
                        .HasColumnType("int");

                    b.Property<int>("TotalStocks")
                        .HasColumnType("int");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ScrapeRunLogs", (string)null);
                });

            modelBuilder.Entity("Meezan.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("NameAr");

                    b.HasIndex("NameEn");

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("Meezan.Domain.Entities.ShariahCompliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("Pct")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StockId")
                        .IsUnique();

                    b.ToTable("ShariahCompliances", (string)null);
                });

            modelBuilder.Entity("Meezan.Domain.Entities.ShariahRefreshLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PctUpdatedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SkippedNoValueCount")
                        .HasColumnType("int");

                    b.Property<int>("SkippedNotFoundCount")
                        .HasColumnType("int");

                    b.Property<int>("StocksFullyRefreshedCount")
                        .HasColumnType("int");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ShariahRefreshLogs", (string)null);
                });

            modelBuilder.Entity("Meezan.Domain.Entities.ShariahSourceOpinion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExtraData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("Percentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SourceLastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "SourceKey")
                        .IsUnique();

                    b.ToTable("ShariahSourceOpinions", (string)null);
                });

            modelBuilder.Entity("Meezan.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameAr")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NameEn")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Stocks", (string)null);
                });

            modelBuilder.Entity("Meezan.Domain.Entities.StockFairValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("FairValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FairValueDiff")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FairValueDiffPct")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MethodsExcludedCount")
                        .HasColumnType("int");

                    b.Property<int>("MethodsUsedCount")
                        .HasColumnType("int");

                    b.Property<string>("PriceComparison")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockId")
                        .IsUnique();

                    b.ToTable("StockFairValues", (string)null);
                });

            modelBuilder.Entity("Meezan.Domain.Entities.StockFairValueMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsOutlier")
                        .HasColumnType("bit");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockFairValueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockFairValueId");

                    b.ToTable("StockFairValueMethods", (string)null);
                });

            modelBuilder.Entity("Meezan.Domain.Entities.StockMarketData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BookValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ClosingPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Currency")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Eps")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("High")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Low")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MarketValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("NominalValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Open")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PbRatio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PeRatio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("SlowDataFetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceLastUpdateText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockId")
                        .IsUnique();

                    b.ToTable("StockMarketData", (string)null);
                });

            modelBuilder.Entity("Meezan.Domain.Entities.StockShariahMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AaoifiHaramEarningPerShare")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("BookValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool?>("CashLiquidityCompliant")
                        .HasColumnType("bit");

                    b.Property<string>("CategoryAr")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CategoryEn")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("CoreActivityCompliant")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Dividend")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DividendType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("FairValueValuation")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HaramEarningsPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool?>("HaramInvestmentsCompliant")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LoansPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Profit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("SourceUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SpHaramEarningPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Zakat")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("StockId")
                        .IsUnique();

                    b.ToTable("StockShariahMetrics", (string)null);
                });

            modelBuilder.Entity("Meezan.Domain.Entities.StockSupportResistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChangePct")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LastPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Pivot")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("R1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("R2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("S1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("S2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockId")
                        .IsUnique();

                    b.ToTable("StockSupportResistance", (string)null);
                });

            modelBuilder.Entity("Meezan.Domain.Entities.UploadHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IndexId")
                        .HasColumnType("int");

                    b.Property<int>("RowsAffected")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IndexId");

                    b.ToTable("UploadHistories", (string)null);
                });

            modelBuilder.Entity("Meezan.Domain.Entities.IndexConstituent", b =>
                {
                    b.HasOne("Meezan.Domain.Entities.Index", "Index")
                        .WithMany("Constituents")
                        .HasForeignKey("IndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Meezan.Domain.Entities.Stock", "Stock")
                        .WithMany("IndexConstituents")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Index");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Meezan.Domain.Entities.ShariahCompliance", b =>
                {
                    b.HasOne("Meezan.Domain.Entities.Stock", "Stock")
                        .WithOne("ShariahCompliance")
                        .HasForeignKey("Meezan.Domain.Entities.ShariahCompliance", "StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Meezan.Domain.Entities.ShariahSourceOpinion", b =>
                {
                    b.HasOne("Meezan.Domain.Entities.Stock", "Stock")
                        .WithMany("ShariahSourceOpinions")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Meezan.Domain.Entities.Stock", b =>
                {
                    b.HasOne("Meezan.Domain.Entities.Sector", "Sector")
                        .WithMany("Stocks")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Meezan.Domain.Entities.StockFairValue", b =>
                {
                    b.HasOne("Meezan.Domain.Entities.Stock", "Stock")
                        .WithOne("FairValue")
                        .HasForeignKey("Meezan.Domain.Entities.StockFairValue", "StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Meezan.Domain.Entities.StockFairValueMethod", b =>
                {
                    b.HasOne("Meezan.Domain.Entities.StockFairValue", "StockFairValue")
                        .WithMany("Methods")
                        .HasForeignKey("StockFairValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockFairValue");
                });

            modelBuilder.Entity("Meezan.Domain.Entities.StockMarketData", b =>
                {
                    b.HasOne("Meezan.Domain.Entities.Stock", "Stock")
                        .WithOne("MarketData")
                        .HasForeignKey("Meezan.Domain.Entities.StockMarketData", "StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Meezan.Domain.Entities.StockShariahMetrics", b =>
                {
                    b.HasOne("Meezan.Domain.Entities.Stock", "Stock")
                        .WithOne("ShariahMetrics")
                        .HasForeignKey("Meezan.Domain.Entities.StockShariahMetrics", "StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Meezan.Domain.Entities.StockSupportResistance", b =>
                {
                    b.HasOne("Meezan.Domain.Entities.Stock", "Stock")
                        .WithOne("SupportResistance")
                        .HasForeignKey("Meezan.Domain.Entities.StockSupportResistance", "StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Meezan.Domain.Entities.UploadHistory", b =>
                {
                    b.HasOne("Meezan.Domain.Entities.Index", "Index")
                        .WithMany("UploadHistories")
                        .HasForeignKey("IndexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Index");
                });

            modelBuilder.Entity("Meezan.Domain.Entities.Index", b =>
                {
                    b.Navigation("Constituents");

                    b.Navigation("UploadHistories");
                });

            modelBuilder.Entity("Meezan.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Meezan.Domain.Entities.Stock", b =>
                {
                    b.Navigation("FairValue");

                    b.Navigation("IndexConstituents");

                    b.Navigation("MarketData");

                    b.Navigation("ShariahCompliance");

                    b.Navigation("ShariahMetrics");

                    b.Navigation("ShariahSourceOpinions");

                    b.Navigation("SupportResistance");
                });

            modelBuilder.Entity("Meezan.Domain.Entities.StockFairValue", b =>
                {
                    b.Navigation("Methods");
                });
#pragma warning restore 612, 618
        }
    }
}
